// as I found two different same code
// i can't clearly understand how they work in behind.

catch (err => {
  console.log(err);
})


// ***************************

catch(console.log);
